apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-demo
  labels:
    app: springboot-k8s-demo
spec:
  type: ClusterIP
  selector:
    app: springboot-k8s-demo
  ports:
  - name: 80-8080
    protocol: TCP
    port: 80
    targetPort: 8080
